spring:
  datasource:
    default:
      url: jdbc:mysql://192.168.3.17:3306/cat?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
      username: root
      password: rootroot
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 10000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

datacenterId: 1
machineId: 1

logging:
  level:
    root: debug